export enum Permission {
    BILLS = "BILLS",
    FUNDS = "FUNDS",
    ATTENDANCE = "ATTENDANCE",

    USERS_SUB_ADMIN = "USERS_SUB_ADMIN",
    USERS_SUPERVISOR = "USERS_SUPERVISOR",
    USERS_WORKER = "USERS_WORKER",

    VENDORS = "VENDORS",
    SALARY = "SALARY",
    INVOICE = "INVOICE",
    BANK_ACCOUNT = "BANK_ACCOUNT",
}
