import path from "path";
import express from "express";
import authRoutes from "./routes/auth.routes";
import billRoutes from "./routes/bill.routes";
import fundroutes from "./routes/funds.routes";
import usersRoutes from "./routes/users.routes";
import partyRoutes from "./routes/party.routes";
import searchRoutes from "./routes/search.routes";
import vendorRoutes from "./routes/vendor.routes";
import accountroutes from "./routes/account.routes";
import dashboardRoutes from "./routes/dashboard.routes";
import attendanceRoutes from "./routes/attendance.routes";
import permissionRoutes from "./routes/permission.routes";
import bankAccountRoutes from "./routes/bankAccount.routes";
import notificationRoutes from "./routes/notification.routes";
import { errorHandler } from "./middlewares/error.middleware";
import { applySecurity } from "./middlewares/security.middleware";

const app = express();
applySecurity(app);

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use("/uploads", express.static(path.join(__dirname, "../uploads")));
app.use("/uploads", express.static("uploads"));
app.use("/api", fundroutes);
app.use("/api", billRoutes);
app.use("/api", usersRoutes);
app.use("/api", vendorRoutes);
app.use("/api/auth", authRoutes);
app.use("/api", attendanceRoutes);
app.use("/api/home", searchRoutes);
app.use("/api", bankAccountRoutes);
app.use("/api/parties", partyRoutes);
app.use("/api/home", dashboardRoutes);
app.use("/api/account", accountroutes);
app.use("/api/home", notificationRoutes);
app.use("/api/permissions", permissionRoutes);
app.use(errorHandler);

export default app;
